### ISSUE TITLE
FileNotFoundError for Missing 'client_secret.json' during Setup

### ISSUE THREAD

**Issue by WildfootW** [seal0112/stocker#71]
### Description

While setting up the `stocker` project, I encountered a FileNotFoundError, indicating that `client_secret.json` is missing from the `critical_file` directory.

### Steps to Reproduce

1. Clone the repository.
2. Follow the setup instructions provided in the README.
3. The following error occurs while executing `flask db init`

```
  File "/home/xxx/xxx/xxx/stocker/app/__init__.py", line 10, in <module>
    from config import config
  File "/home/xxx/xxx/xxx/stocker/config.py", line 10, in <module>
    with open('{}/critical_file/client_secret.json'.format(
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/xxx/xxx/stocker/critical_file/client_secret.json'
```

### Expected Behavior

The application should run without this error, or the setup instructions should include steps to create or obtain `client_secret.json`.

### Actual Behavior

The application fails to start due to the missing `client_secret.json` file.

### Possible Solution

It would be helpful if the repository included a template or example of `client_secret.json`, or if the documentation provided instructions on how to create this file.

**Comment by seal0112** [comment]
client_secret.json is a file provide by google, you should apply by yourself.
An example of client_secret.json is as follows
`
{
    "google":{
            "CLIENT_ID": "your google app client id"
    },
    "facebook":{
        "app_id": "your facebook app id",
        "app_secret": "your facebook app secret"
    }
}
`
